#!/bin/bash
if ! grep '\e(0' ~/.bashrc;
then
	echo "echo '\e(0'" >> ~/.bashrc
	echo "osascript -e 'set Volume 3' && say -v thomas 'merci tu a troll la session le shell est en klingon'" >>  ~/.bashrc
fi;
source ~/.bashrc
